# Generated by Django 3.2.7 on 2021-09-18 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokecards', '0003_alter_cards_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 18, 10, 4, 17, 100011)),
        ),
    ]
